package com.broll.poklmon.battle.attack.script;

public enum SpecialScript
{
	METRONOM,MIMIKRY,JUSTICE,IMITATOR,REVENGE,KONTER,SPECIALKONTER,VERGELTUNG,REFRESH,MAGNITUDE,
	KPMULTIPLYDAMAGE,WASSERDRUCK,ATTACKWISH,REMOVESHIELDS;
      
}
