package com.broll.poklmon.battle.render;

public enum BattleSequences {

	
	PLAYER_INTRO,ENEMY_INTRO,WILD_POKLMON_INTRO,THROW_POKLBALL,
	POKLMON_DEFEATED,BATTLE_WON,BATTLE_LOST,PLAYER_USE_ITEM,
	ENEMY_USE_ITEM,PLAYER_CHANGE_POKLMON,ENEMY_CHANGE_POKLMON,
	PLAYER_ESCAPE,ENEMY_ESCAPE,
	POKLMON_TAKING_DAMAGE,POKLMON_ATTRIBUTE_CHANGE,POKLMON_HEAL_ANIMATION,
	PLAYER_GAINEXP,POKLMON_EVOLUTION,TRAINER_INTRO;
	
}
